In [1]:
import numpy as np

In [13]:
x = np.arange(6).reshape(2,3)
print('x.shape =', x.shape)
x

x.shape = (2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
mask = np.array([
    [True, True, False],
    [False, True, True]])
print('mask.shape =', mask.shape)
mask

mask.shape = (2, 3)


array([[ True,  True, False],
       [False,  True,  True]])

In [4]:
x[mask]


array([0, 1, 4, 5])

^
What's going on? Why asked to flatten the data yo?!


_____

In [11]:
# expected = np.array([
#     [0, 1, 0],
#     [0, 4, 5]])
# expected

In [16]:
np.where(mask, x, 0)

array([[0, 1, 0],
       [0, 4, 5]])